resources:
- ../prod
patches:
- target:
    version: v1
    kind: Service
    name: typetunerweb
  path: nodeport_service.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    name: typetunerweb
  path: patch_image_pull.yaml
