name: Prune images
on:
  workflow_run:
    workflows: [Build Docker fastcgi image]
    types: [completed]

jobs:
  prune:
    runs-on: ubuntu-latest
    steps:
    - name: prune
      uses: vlaurin/action-ghcr-prune@v0.5.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        organization: silnrsi
        container: typetunerweb
        dry-run: false
        keep-younger-than: 7
        keep-last: 6
        prune-tags-regexes: ^.*$
        prune-untagged: true
